apiVersion: v1
kind: Namespace
metadata:
  name: scf-benchmark

---

apiVersion: v1
kind: Service
metadata:
  name: eks-flask-demo-svc
  namespace: scf-benchmark
spec:
  selector:
    app: flask-web
  ports:
  - protocol: TCP
    port: 9000
    targetPort: eks-flask-demo
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-web
  namespace: scf-benchmark
spec:
  selector:
    matchLabels:
      app: flask-web
  replicas: 1
  template:
    metadata:
      labels:
        app: flask-web
    spec:
      containers:
      - name: eks-flask-demo
        image: zhengquan/eks-flask-demo:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
